# Generated by cucumber-sinatra. (Sun Jan 23 17:44:48 +0000 2011)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '../../webapp.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Skweets

class SkweetsWorld
  include Capybara
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  SkweetsWorld.new
end

# Use a different database in cukes than when running in production mode.
# DataMapper.setup(:default, {:adapter  => "redis", :db => 1})
# Clean up after test runs.
After do
  Tweet.destroy!
end
