if File.exists?('features')
  require 'cucumber'
  require 'cucumber/rake/task'
  Cucumber::Rake::Task.new(:features) do |t|
    t.cucumber_opts = "features --format pretty"
  end
end

if File.exists?('specs')
  require 'rspec/core/rake_task'
  desc "Run all examples"
  RSpec::Core::RakeTask.new(:specs) do |t|
    t.rspec_opts  = ['--color', '--format', 'nested']
  end
end

task :default => [:specs, :features].select{|t| Rake::Task.task_defined?(t)}

task :start do
  require 'lib/firehose_coupling'
  FirehoseCoupling.run!
end
